routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::resource('users', UserController::class)->only(['index','store','edit','update','destroy'])->names('users');
Route::resource('products', ProductController::class)->only(['index','store','edit','update','destroy'])->names('products');

Route::get('change_status/users/{user}', 'App\Http\Controllers\UserController@change_status_user')->name('change.status.user');
Route::get('change_status/products/{product}', 'App\Http\Controllers\ProductController@change_status_product')->name('change.status.product');

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    use HasFactory;

    protected $fillable = [
    	'sku',
    	'name',
    	'quantity',
    	'price',
    	'description',
    	'deleted'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'username',
        'dateofbirth',
        'state',
        'deleted',
        
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        return view('index');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Products;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        $products = Products::get();
        return view('products', compact('products'));
        // return $products;
    }
    public function edit(Products $product)
    {
        return view('productedit', compact('product'));
    }
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'quantity' => 'required',
        ]);
        $product = Products::create($request->all());
        return redirect()->route('products.index')->with('info', 'Producto creado con exito.');
    }
    public function update(Request $request, Products $product)
    {
        $request->validate([
            'name' => 'required',
            'price' => 'required',
            'quantity' => 'required',
        ]);
        $product->update($request->all());
        return redirect()->route('products.index')->with('info', 'Producto editado con exito.');
    }
    public function change_status_product(Products $product)
    {
        if ($product->deleted == 1) {
            $product->update(['deleted'=>0]);
            return redirect()->route('products.index')->with('info', 'Producto desactivado con exito.');
        } else {
            $product->update(['deleted'=>1]);
            return redirect()->route('products.index')->with('info', 'Producto activado con exito.');
        } 
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $users = User::get();
        return view('users', compact('users'));
        // return $users;
    }
    public function edit(User $user)
    {
        return view('useredit', compact('user'));
    }
    public function store(Request $request)
    {
        $user = User::create($request->all());
        return redirect()->route('users.index')->with('info', 'Usuario creado con exito.');
    }
    public function update(Request $request, User $user)
    {
        $user->update($request->all());
        return redirect()->route('users.index')->with('info', 'Usuario editado con exito.');
    }
    public function change_status_user(User $user)
    {
        if ($user->deleted == 1) {
            $user->update(['deleted'=>0]);
            return redirect()->route('users.index')->with('info', 'Usuario desactivado con exito.');
        } else {
            $user->update(['deleted'=>1]);
            return redirect()->route('users.index')->with('info', 'Usuario activado con exito.');
        } 
    }
}

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>@yield('title')</title>
  <link rel="stylesheet" href="{{asset('template/css/iconfonts/font-awesome/css/all.min.css')}}">
  <link rel="stylesheet" href="{{asset('template/css/vendor.bundle.base.css')}}">
  <link rel="stylesheet" href="{{asset('template/css/vendor.bundle.addons.css')}}">
  <link rel="stylesheet" href="{{asset('template/css/style.css')}}">
  <link rel="shortcut icon" href="" />
  @yield('styles')
</head>
<body class="sidebar-fixed">
  <div class="container-scroller">
    @include('layouts.header')
    <div class="container-fluid page-body-wrapper">
     @include('layouts.sidebar')
     <div class="main-panel">
      @yield('content')
      @include('layouts.footer')
    </div>
  </div>
</div>
<script src="{{asset('template/js/vendor.bundle.base.js')}}"></script>
<script src="{{asset('template/js/vendor.bundle.addons.js')}}"></script>
<script src="{{asset('template/js/off-canvas.js')}}"></script>
<script src="{{asset('template/js/hoverable-collapse.js')}}"></script>
<script src="{{asset('template/js/misc.js')}}"></script>
<script src="{{asset('template/js/settings.js')}}"></script>
<script src="{{asset('template/js/todolist.js')}}"></script>
<script src="{{asset('template/js/dashboard.js')}}"></script>
@yield('scripts')

</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer">
	<div class="d-sm-flex justify-content-center justify-content-sm-between">
		<span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2022. All rights reserved.</span>
	</div>
</footer>

resources/views/layouts/header.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row default-layout-navbar">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo" href="#"><img src="" alt="Direct English"/></a>
    <a class="navbar-brand brand-logo-mini" href="#"><img src="" alt=""/></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="fas fa-bars"></span>
    </button>
    <ul class="navbar-nav">
      <li class="nav-item nav-search d-none d-md-flex">
        <div class="nav-link">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="fas fa-search"></i>
              </span>
            </div>
            <input type="text" class="form-control" placeholder="Search" aria-label="Search">
          </div>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
          <img src="images/faces/face5.jpg" alt="Perfil"/>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
          <div class="dropdown-divider"></div>
          <form action="#" method="POST">
            @csrf
            <button class="dropdown-item">
              <i class="fas fa-power-off text-primary"></i>
              Logout
            </button>
          </form>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="fas fa-bars"></span>
    </button>
  </div>
</nav>

resources/views/layouts/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item nav-profile">
      <div class="nav-link">
        <div class="profile-image">
        </div>
        <div class="profile-name">
          <p class="name">
            Usuario
          </p>
        </div>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ route('users.index') }}">
        <i class="far fa-user menu-icon"></i>
        <span class="menu-title">Usuarios</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ route('products.index') }}">
        <i class="fa fa-address-book menu-icon"></i>
        <span class="menu-title">Productos</span>
      </a>
    </li>
  </ul>
</nav>

resources/views/productedit.blade.php
 @extends('index')

 @section('title','Edición de producto')

 @section('styles')
 @endsection

 @section('content')
 <div class="content-wrapper">
 	<div class="page-header">
 		<h3 class="page-title">
 			Productos
 		</h3>
 		<nav aria-label="breadcrumb">
 			<ol class="breadcrumb breadcrumb-custom">
 				<li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
 				<li class="breadcrumb-item" aria-current="page"><a href="{{ route('products.index') }}">Productos</a></li>
 				<li class="breadcrumb-item active" aria-current="page">Editar</li>
 			</ol>
 		</nav>
 	</div>
 	<div class="card">
 		<div class="card-body">
 			<div class="row">
 				<div class="col-lg-12 grid-margin">
 					@if(session('info'))
 					<div class="alert alert-success">
 						<strong>{{session('info')}}</strong>
 					</div>
 					@endif
 					@error(session('name'))
 					<div class="alert alert-danger ">
 						<strong>{{ $message }}</strong>
 					</div>
 					@enderror
 					<h4 class="card-title">Datos del producto</h4>
 					{!! Form::model($product, ['route' => ['products.update', $product], 'method' => 'put']) !!}
 					<fieldset>
 						<div class="row">
 							<div class="col-4">	
 								<div class="form-group">
 									<label for="sku">Sku</label>
 									<input value="{{ $product->sku }}" id="sku" class="form-control" name="sku" type="text">
 								</div>
 							</div>
 							<div class="col-4">	
 								<div class="form-group">
 									<label for="name">Nombre</label>
 									<input required value="{{ $product->name }}" id="name" class="form-control" name="name" type="text">
 								</div>
 							</div>
 							<div class="col-4">	
 								<div class="form-group">
 									<label for="price">Precio</label>
 									<input required step="0.01" value="{{ $product->price }}" id="price" class="form-control" name="price" type="number">
 								</div>
 							</div>
 							<div class="col-4">	
 								<div class="form-group">
 									<label for="quantity">Cantidad</label>
 									<input required value="{{ $product->quantity }}" id="quantity" class="form-control" name="quantity" type="number">
 								</div>
 							</div>
 							<div class="col-4">	
 								<div class="form-group">
 									<label for="description">Descripción</label>
 									<input  value="{{ $product->description }}" id="description" class="form-control" name="description" type="text">
 								</div>
 							</div>
 							<div class="col-4">
				                <div class="form-group">
				                  <label for="deleted">Estatus</label>
				                  <select name="deleted" class="form-control" >
				                    <option value="1"  @if($product->deleted == '1') selected @endif>Activo</option>
				                    <option value="0"  @if($product->deleted == '0') selected @endif>Inactivo</option>
				                  </select>
				                </div>
				            </div>
 						</div>
 						{!! Form::submit('Editar', ['class' => 'btn btn-primary']) !!}
 					</fieldset>
 					{!! Form::close() !!}
 				</div>
 			</div>
 		</div>
 	</div>
 	@endsection

 	@section('scripts')
 	<script src="{{asset('template/js/form-validation.js')}}"></script>
 	<script src="{{asset('template/js/bt-maxLength.js')}}"></script>
 	@endsection

resources/views/products.blade.php
@extends('index')

@section('title','Productos')

@section('styles')
@endsection

@section('content')
<div class="content-wrapper">
  <div class="page-header">
    <h3 class="page-title">
      Productos
    </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        @can('admin.home')
        <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
        @endcan
        <li class="breadcrumb-item active" aria-current="page">Productos</li>
      </ol>
    </nav>
  </div>
  <div class="card">
    <div class="card-body">
      @if(session('info'))
      <div class="alert alert-success">
        <strong>{{session('info')}}</strong>
      </div>
      @endif
      @error(session('name'))
      <div class="alert alert-danger ">
        <strong>{{ $message }}</strong>
      </div>
      @enderror
      <div class="d-flex justify-content-between">
        <h4 class="card-title">Productos</h4>
        <a href="" class="nav-link" type="button" data-toggle="modal" data-target="#exampleModal-4" data-whatever="@mdo">
          <span class="btn btn-outline-primary btn-icon-text btn-sm">Crear</span>
        </a>
        <div class="nav-link modal fade" id="exampleModal-4" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Nuevo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {!! Form::open(['route' => 'products.store']) !!}
              <div class="modal-body">
                <div class="form-group">
                  {!! Form::label('sku', 'SKU') !!}
                  {!! Form::text('sku', null, ['class' => 'form-control', 'placeholder' => 'Ingrese el sku']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('name', 'Nombre') !!}
                  {!! Form::text('name', null, ['required' => 'true','class' => 'form-control', 'placeholder' => 'Ingrese el nombre']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('quantity', 'Cantidad') !!}
                  {!! Form::number('quantity', null, ['required' => 'true','class' => 'form-control', 'placeholder' => 'Ingrese la cantidad']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('price', 'Precio') !!}
                  {!! Form::number('price', null, ['required' => 'true','step' => '0.01', 'class' => 'form-control', 'placeholder' => 'Ingrese el precio']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('description', 'Descipción') !!}
                  {!! Form::text('description', null, ['class' => 'form-control', 'placeholder' => 'Ingrese la descipción']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('deleted', 'Estatus') !!}
                  <select name="deleted" class="form-control" required>
                    <option value="">Seleccione...</option>
                    <option value="1">Activo</option>
                    <option value="0">Inactivo</option>
                  </select>
                </div>
              </div>
              <div class="modal-footer">
                {!! Form::submit('Crear', ['class' => 'btn btn-success']) !!}
                <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
              </div>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="table-responsive">
            <table id="order-listing" class="table">
              <thead>
                <tr>
                  <th>Sku</th>
                  <th>Nombre</th>
                  <th>Cantidad</th>
                  <th>Precio</th>
                  <th>Descipción</th>
                  <th>Eliminado</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                @foreach($products as $key => $product)
                <tr>
                  <td>{{$product->sku}}</td>
                  <td>{{$product->name}}</td>
                  <td>{{$product->quantity}}</td>
                  <td>{{$product->price}}</td>
                  <td>{{$product->description}}</td>
                    @if ($product->deleted == 1)
                    <td>
                        <a class="jsgrid-button btn btn-success" href="{{route('change.status.product', $product)}}" title="Desactivar">
                            <!-- Activa --> <i class="fas fa-check"></i>
                        </a>
                    </td>
                    @else
                    <td>
                        <a class="jsgrid-button btn btn-danger" href="{{route('change.status.product', $product)}}" title="Activar">
                            <!-- Inactiva --> <i class="fas fa-times"></i>
                        </a>
                    </td>
                    @endif
                  <td>         
                    <a class="btn btn-outline-info" href="{{ route('products.edit',$product) }}" title="Editar">
                      <i class="far fa-edit"></i>
                    </a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script src="{{asset('template/js/data-table.js')}}"></script>
@endsection

resources/views/useredit.blade.php
 @extends('index')

 @section('title','Edición de Usuario')

 @section('styles')
 @endsection

 @section('content')
 <div class="content-wrapper">
  <div class="page-header">
    <h3 class="page-title">
      Usuarios
    </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb breadcrumb-custom">
        <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
        <li class="breadcrumb-item" aria-current="page"><a href="{{ route('users.index') }}">Usuarios</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
      </ol>
    </nav>
  </div>
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-lg-12 grid-margin">
          @if(session('info'))
          <div class="alert alert-success">
            <strong>{{session('info')}}</strong>
          </div>
          @endif
          @error(session('name'))
          <div class="alert alert-danger ">
            <strong>{{ $message }}</strong>
          </div>
          @enderror
          <h4 class="card-title">Datos del Usuario</h4>
          {!! Form::model($user, ['route' => ['users.update', $user], 'method' => 'put']) !!}
          <fieldset>
            <div class="row">
              <div class="col-4"> 
                <div class="form-group">
                  <label for="name">Nombre</label>
                  <input required value="{{ $user->name }}" id="name" class="form-control" name="name" type="text">
                </div>
              </div>
              <div class="col-4"> 
                <div class="form-group">
                  <label for="email">Correo</label>
                  <input required value="{{ $user->email }}" id="email" class="form-control" name="email" type="email">
                </div>
              </div>
              <div class="col-4"> 
                <div class="form-group">
                  <label for="phone">Teléfono</label>
                  <input required value="{{ $user->phone }}" id="phone" class="form-control" name="phone" type="text">
                </div>
              </div>
              <div class="col-4"> 
                <div class="form-group">
                  <label for="username">Usuario</label>
                  <input required value="{{ $user->username }}" id="username" class="form-control" name="username" type="text">
                </div>
              </div>
              <div class="col-4"> 
                <div class="form-group">
                  <label for="dateofbirth">Fecha de nacimiento </label>
                  <input required value="{{ $user->dateofbirth }}" id="dateofbirth" class="form-control" name="dateofbirth" type="date">
                </div>
              </div>
              <div class="col-4"> 
                <div class="form-group">
                  <label for="state">Estado </label>
                  <input required value="{{ $user->state }}" id="state" class="form-control" name="state" type="text">
                </div>
              </div>
              <div class="col-4">
                <div class="form-group">
                  <label for="deleted">Estatus</label>
                  <select name="deleted" class="form-control" >
                    <option value="1"  @if($user->deleted == '1') selected @endif>Activo</option>
                    <option value="0"  @if($user->deleted == '0') selected @endif>Inactivo</option>
                  </select>
                </div>
              </div>
            </div>
            {!! Form::submit('Editar', ['class' => 'btn btn-primary']) !!}
          </fieldset>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
  @endsection

  @section('scripts')
  <script src="{{asset('template/js/form-validation.js')}}"></script>
  <script src="{{asset('template/js/bt-maxLength.js')}}"></script>
  @endsection

resources/views/users.blade.php
@extends('index')

@section('title','Usuarios')

@section('styles')
@endsection

@section('content')
<div class="content-wrapper">
  <div class="page-header">
    <h3 class="page-title">
      Usuarios
    </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        @can('admin.home')
        <li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
        @endcan
        <li class="breadcrumb-item active" aria-current="page">Usuarios</li>
      </ol>
    </nav>
  </div>
  <div class="card">
    <div class="card-body">
      @if(session('info'))
      <div class="alert alert-success">
        <strong>{{session('info')}}</strong>
      </div>
      @endif
      @error(session('name'))
      <div class="alert alert-danger ">
        <strong>{{ $message }}</strong>
      </div>
      @enderror
      <div class="d-flex justify-content-between">
        <h4 class="card-title">Usuarios</h4>
        <a href="" class="nav-link" type="button" data-toggle="modal" data-target="#exampleModal-4" data-whatever="@mdo">
          <span class="btn btn-outline-primary btn-icon-text btn-sm">Crear</span>
        </a>
        <div class="nav-link modal fade" id="exampleModal-4" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">Nuevo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {!! Form::open(['route' => 'users.store']) !!}
              <div class="modal-body">
                <div class="form-group">
                  {!! Form::label('name', 'Nombre') !!}
                  {!! Form::text('name', null, ['required' => 'true','class' => 'form-control', 'placeholder' => 'Ingrese el nombre']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('phone', 'Teléfono') !!}
                  {!! Form::text('phone', null, ['required' => 'true','class' => 'form-control', 'placeholder' => 'Ingrese el teléfono']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('username', 'Usuario') !!}
                  {!! Form::text('username', null, ['required' => 'true','class' => 'form-control', 'placeholder' => 'Ingrese el usuario']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('dateofbirth', 'Fecha de nacimiento') !!}
                  {!! Form::date('dateofbirth', null, ['required' => 'true','class' => 'form-control', 'placeholder' => 'Ingrese el fecha de nacimiento']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('state', 'Estado') !!}
                  {!! Form::text('state', null, ['required' => 'true','class' => 'form-control', 'placeholder' => 'Ingrese el estado']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('email', 'Correo') !!}
                  {!! Form::email('email', null, ['required' => 'true','class' => 'form-control', 'placeholder' => 'Ingrese el correo']) !!}
                </div>
                <div class="form-group">
                  {!! Form::label('status', 'Estatus') !!}
                    <select name="delete" class="form-control" required>
                      <option value="">Seleccione...</option>
                      <option value="1">Activo</option>
                      <option value="0">Inactivo</option>
                    </select>
                </div>
                <div class="form-group">
                  {!! Form::label('password', 'Contraseña') !!}
                  {!! Form::text('password', null, ['required' => 'true','class' => 'form-control', 'placeholder' => 'Ingrese la contraseña']) !!}
                </div>
              </div>
              <div class="modal-footer">
                {!! Form::submit('Crear', ['class' => 'btn btn-success']) !!}
                <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
              </div>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="table-responsive">
            <table id="order-listing" class="table">
              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Teléfono</th>
                  <th>Usuario</th>
                  <th>Fecha de nacimiento,</th>
                  <th>Correo,</th>
                  <th>Estado</th>
                  <th>Eliminado</th>
                  <th>Acciones</th>
                </tr>
              </thead>
              <tbody>
                @foreach($users as $key => $user)
                <tr>
                  <td>{{$user->name}}</td>
                  <td>{{$user->phone}}</td>
                  <td>{{$user->username}}</td>
                  <td>{{$user->dateofbirth}}</td>
                  <td>{{$user->email}}</td>
                  <td>{{$user->state}}</td>
                  @if ($user->deleted == 1)
                  <td>
                      <a class="jsgrid-button btn btn-success" href="{{route('change.status.user', $user)}}" title="Desactivar">
                          <!-- Activa --> <i class="fas fa-check"></i>
                      </a>
                  </td>
                  @else
                  <td>
                      <a class="jsgrid-button btn btn-danger" href="{{route('change.status.user', $user)}}" title="Activar">
                          <!-- Inactiva --> <i class="fas fa-times"></i>
                      </a>
                  </td>
                  @endif
                  <td>       
                    <a class="btn btn-outline-info" href="{{ route('users.edit',$user) }}" title="Editar">
                      <i class="far fa-edit"></i>
                    </a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('scripts')
<script src="{{asset('template/js/data-table.js')}}"></script>
@endsection